reachy:
  head:
    neck:
      orbita_actuator:
        id: 40
    neck_fan:
      fan:
        id: 40
    l_antenna:
      dxl_motor:
        type: XL-320
        id: 30
    l_antenna_fan:
      fan:
        id: 30
    r_antenna:
      dxl_motor:
        type: XL-320
        id: 31
    r_antenna_fan:
      fan:
        id: 31